.TH LIGHTWALLET "1" "December 2022" "lightwalletd v0.1.2" "User Commands"
.SH NAME
lightwalletd \- manual page for hush lightwalletd v0.1.2
.SH DESCRIPTION
.B lightwalletd
runs a lightwallet daemon for a Hush Silent Dragon Lite node.
.PP
In order to ensure you are adequately protecting your privacy when using Hush,
please see <https://hush.is/security/>.
.SS "Usage:"
.TP
.B lightwalletd [options]
Start Hush lightwalletd
.TP
lightwalletd --help
List available command line options
.TP
lightwalletd --version
Display version information
.SH OPTIONS
.HP
\fB\-help | -h | -?
.IP
Display command line options
.HP
\fB\--hush-conf-path\fR [conf_file location]
.IP
Configures your HUSH3.conf file location to pull RPC creds from (default "./HUSH3.conf")
.HP
\fB\--data-dir\fR [location]
.IP
Configures your lightwalletd data directory (such as db) (default "/var/lib/lightwalletd")
.HP
\fB\--grpc-bind-addr \fRlocalhost:chosen_port
.IP
The address to listen for grpc on (default "localhost:9067")
.HP
\fB\--no-tls
.IP
Run without TLS, only safe if a reverse proxy like nginx does TLS on localhost.
.HP
\fB\--cache-size \fRint
.IP
Set number of blocks to hold in the cache (default 40000)
.HP
\fB\--log-file \fRstring
.IP
Set log file to write to
.HP
\fB\--log-level \fRuint
.IP
log level (logrus 1-7) (default 4)
.HP
\fB\--tls-cert \fRstring
.IP
the path to a TLS certificate (optional)
.HP
\fB\--tls-key \fRstring
.IP
the path to a TLS key file (optional)

.SH COPYRIGHT
In order to ensure you are adequately protecting your privacy when using Hush,
please see <https://hush.is/security/>.

Copyright (C) 2021-2022 Jahway603 and The Hush Developers

This is experimental Free Software! Fuck Yeah!!!!!

Distributed under the GPLv3 software license, see the accompanying file COPYING
or <https://www.gnu.org/licenses/gpl-3.0.en.html>.
